Failure # 1 (occurred at 2022-06-21_03-45-16)
[36mray::ImplicitFunc.train()[39m (pid=32604, ip=127.0.0.1, repr=func)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base_env/lib/python3.9/site-packages/ray/tune/trainable.py", line 360, in train
    result = self.step()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base_env/lib/python3.9/site-packages/ray/tune/function_runner.py", line 385, in step
    result = self._results_queue.get(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base_env/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base_env/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

[36mray::ImplicitFunc.train()[39m (pid=32604, ip=127.0.0.1, repr=func)
ray.exceptions.TaskCancelledError: Task: TaskID(594c3bb38e5948119ee05902757fe5388536819e01000000) was cancelled
